// <auto-generated />
using System;
using BestRecipes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestRecipes.Migrations
{
    [DbContext(typeof(BestRecipesContext))]
    [Migration("20260113015404_AddDescriptionToRecipe")]
    partial class AddDescriptionToRecipe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BestRecipes.Data.BestRecipesUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BestRecipes.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(800),
                            DateUpdated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(820),
                            Description = "Start your meal with delicious appetizers.",
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(822),
                            DateUpdated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(822),
                            Description = "Hearty and satisfying main course recipes.",
                            Name = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(824),
                            DateUpdated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(825),
                            Description = "Sweet treats to end your meal.",
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Challenge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(1170),
                            DateUpdated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(1172),
                            Details = "Create the most refreshing and healthy summer salad.",
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Salad Challenge",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(1177),
                            DateUpdated = new DateTime(2026, 1, 13, 9, 54, 2, 457, DateTimeKind.Local).AddTicks(1177),
                            Details = "Bake a delicious dessert perfect for the holiday season.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Holiday Dessert Challenge",
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This recipe is fantastic! My family loved it.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1360),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1360),
                            RecipeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "I found the instructions a bit confusing, but the end result was great.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1361),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1362),
                            RecipeId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Delicious! I will definitely make this again.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1363),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1364),
                            RecipeId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Favourite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1518),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1519),
                            RecipeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1520),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1521),
                            RecipeId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1522),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1522),
                            RecipeId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownVote")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpVote")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1696),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1697),
                            DownVote = 10,
                            Name = "Sugar",
                            UnitOfMeasurement = "Cups",
                            UpVote = 150
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1698),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1699),
                            DownVote = 5,
                            Name = "Salt",
                            UnitOfMeasurement = "Teaspoons",
                            UpVote = 200
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1700),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(1701),
                            DownVote = 8,
                            Name = "Flour",
                            UnitOfMeasurement = "Cups",
                            UpVote = 180
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookingDuration")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("ServingSize")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(2045),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(2046),
                            Description = "Fluffy and light pancakes perfect for breakfast.",
                            IngredientId = 0,
                            Instructions = "Mix ingredients, cook on griddle, serve with syrup.",
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Classic Pancakes",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(2048),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(2049),
                            Description = "Crisp romaine lettuce with creamy Caesar dressing.",
                            IngredientId = 0,
                            Instructions = "Toss lettuce with dressing, add croutons and cheese.",
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Caesar Salad",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(2050),
                            DateUpdated = new DateTime(2026, 1, 13, 1, 54, 2, 457, DateTimeKind.Utc).AddTicks(2051),
                            Description = "Chewy cookies loaded with chocolate chips.",
                            IngredientId = 0,
                            Instructions = "Mix dough, fold in chocolate chips, bake until golden.",
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Chocolate Chip Cookies",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
