// <auto-generated />
using System;
using BestRecipes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestRecipes.Migrations
{
    [DbContext(typeof(BestRecipesContext))]
    [Migration("20260106132742_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BestRecipes.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(7847),
                            DateUpdated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(7869),
                            Description = "Start your meal with delicious appetizers.",
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(7873),
                            DateUpdated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(7874),
                            Description = "Hearty and satisfying main course recipes.",
                            Name = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(7876),
                            DateUpdated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(7877),
                            Description = "Sweet treats to end your meal.",
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Challenge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(8351),
                            DateUpdated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(8354),
                            Details = "Create the most refreshing and healthy summer salad.",
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Salad Challenge",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(8357),
                            DateUpdated = new DateTime(2026, 1, 6, 21, 27, 41, 144, DateTimeKind.Local).AddTicks(8358),
                            Details = "Bake a delicious dessert perfect for the holiday season.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Holiday Dessert Challenge",
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This recipe is fantastic! My family loved it.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8576),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8577),
                            RecipeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "I found the instructions a bit confusing, but the end result was great.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8579),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8579),
                            RecipeId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Delicious! I will definitely make this again.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8581),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8582),
                            RecipeId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Favourite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8792),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8793),
                            RecipeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8795),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8795),
                            RecipeId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8797),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(8797),
                            RecipeId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownVote")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpVote")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9007),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9008),
                            DownVote = 10,
                            Name = "Sugar",
                            UnitOfMeasurement = "Cups",
                            UpVote = 150
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9010),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9010),
                            DownVote = 5,
                            Name = "Salt",
                            UnitOfMeasurement = "Teaspoons",
                            UpVote = 200
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9012),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9013),
                            DownVote = 8,
                            Name = "Flour",
                            UnitOfMeasurement = "Cups",
                            UpVote = 180
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookingDuration")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("ServingSize")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9369),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9370),
                            Description = "Fluffy and light pancakes perfect for breakfast.",
                            IngredientId = 0,
                            Instructions = "Mix ingredients, cook on griddle, serve with syrup.",
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Classic Pancakes",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9372),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9373),
                            Description = "Crisp romaine lettuce with creamy Caesar dressing.",
                            IngredientId = 0,
                            Instructions = "Toss lettuce with dressing, add croutons and cheese.",
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Caesar Salad",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9375),
                            DateUpdated = new DateTime(2026, 1, 6, 13, 27, 41, 144, DateTimeKind.Utc).AddTicks(9375),
                            Description = "Chewy cookies loaded with chocolate chips.",
                            IngredientId = 0,
                            Instructions = "Mix dough, fold in chocolate chips, bake until golden.",
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Chocolate Chip Cookies",
                            UserId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
