// <auto-generated />
using System;
using BestRecipes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestRecipes.Migrations
{
    [DbContext(typeof(BestRecipesContext))]
    [Migration("20260118080608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BestRecipes.Data.BestRecipesUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "effc9282-d3cc-4c60-be8d-961e804e6686",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBjKhQZ2YX5AvP2oyK9FstH19t4RpeCi5foesvJoAlbJDuSCNnwS8XBG6QYtgnySMA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "697ba9fc-866c-422a-8707-3c67453d9db1",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9309),
                            DateUpdated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9321),
                            Description = "Start your meal with delicious appetizers.",
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9322),
                            DateUpdated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9323),
                            Description = "Hearty and satisfying main course recipes.",
                            Name = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9324),
                            DateUpdated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9324),
                            Description = "Sweet treats to end your meal.",
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Challenge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9805),
                            DateUpdated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9805),
                            Details = "Create the most refreshing and healthy summer salad.",
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Salad Challenge",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9807),
                            DateUpdated = new DateTime(2026, 1, 18, 16, 6, 8, 198, DateTimeKind.Local).AddTicks(9807),
                            Details = "Bake a delicious dessert perfect for the holiday season.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Holiday Dessert Challenge",
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This recipe is fantastic! My family loved it.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9887),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9887),
                            RecipeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "I found the instructions a bit confusing, but the end result was great.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9888),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9889),
                            RecipeId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Delicious! I will definitely make this again.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9890),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9890),
                            RecipeId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Favourite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9960),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9961),
                            RecipeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9962),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9962),
                            RecipeId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9963),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9963),
                            RecipeId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownVote")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpVote")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Pantry",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "All-Purpose Flour",
                            UpVote = 180
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pantry",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Granulated Sugar",
                            UpVote = 150
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pantry",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 2,
                            Name = "Olive Oil",
                            UpVote = 210
                        },
                        new
                        {
                            Id = 4,
                            Category = "Dairy",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Unsalted Butter",
                            UpVote = 95
                        },
                        new
                        {
                            Id = 5,
                            Category = "Dairy",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Whole Milk",
                            UpVote = 70
                        },
                        new
                        {
                            Id = 6,
                            Category = "Produce",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 1,
                            Name = "Garlic",
                            UpVote = 300
                        },
                        new
                        {
                            Id = 7,
                            Category = "Produce",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 5,
                            Name = "Yellow Onion",
                            UpVote = 120
                        },
                        new
                        {
                            Id = 8,
                            Category = "Spices",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Kosher Salt",
                            UpVote = 400
                        },
                        new
                        {
                            Id = 9,
                            Category = "Spices",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Black Pepper",
                            UpVote = 250
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookingDuration")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("ServingSize")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9592),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9592),
                            Description = "Fluffy and light pancakes perfect for breakfast.",
                            Instructions = "Mix ingredients, cook on griddle, serve with syrup.",
                            IsTrending = false,
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Classic Pancakes",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9593),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9594),
                            Description = "Crisp romaine lettuce with creamy Caesar dressing.",
                            Instructions = "Toss lettuce with dressing, add croutons and cheese.",
                            IsTrending = false,
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Caesar Salad",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9595),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9595),
                            Description = "Chewy cookies loaded with chocolate chips.",
                            Instructions = "Mix dough, fold in chocolate chips, bake until golden.",
                            IsTrending = false,
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Chocolate Chip Cookies",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredient");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9665),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9665),
                            Id = 0,
                            Notes = "sifted",
                            Quantity = 200m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9666),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9667),
                            Id = 0,
                            Notes = "",
                            Quantity = 30m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9668),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9668),
                            Id = 0,
                            Notes = "room temperature",
                            Quantity = 250m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9669),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9670),
                            Id = 0,
                            Notes = "melted",
                            Quantity = 50m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 8,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9671),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9672),
                            Id = 0,
                            Notes = "pinch",
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9674),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9674),
                            Id = 0,
                            Notes = "finely chopped",
                            Quantity = 0.25m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 3,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9675),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9675),
                            Id = 0,
                            Notes = "for dressing",
                            Quantity = 50m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 8,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9676),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9677),
                            Id = 0,
                            Notes = "to taste",
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 9,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9678),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9678),
                            Id = 0,
                            Notes = "freshly ground",
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 1,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9679),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9679),
                            Id = 0,
                            Notes = "sifted",
                            Quantity = 180m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 2,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9680),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9681),
                            Id = 0,
                            Notes = "",
                            Quantity = 100m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 4,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9682),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9682),
                            Id = 0,
                            Notes = "softened",
                            Quantity = 100m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 8,
                            DateCreated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9683),
                            DateUpdated = new DateTime(2026, 1, 18, 8, 6, 8, 198, DateTimeKind.Utc).AddTicks(9683),
                            Id = 0,
                            Notes = "to balance sweetness",
                            Quantity = 0.5m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BestRecipes.Domain.RecipeIngredient", b =>
                {
                    b.HasOne("BestRecipes.Domain.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BestRecipes.Domain.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BestRecipes.Domain.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("BestRecipes.Domain.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
