// <auto-generated />
using System;
using BestRecipes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestRecipes.Migrations
{
    [DbContext(typeof(BestRecipesContext))]
    partial class BestRecipesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BestRecipes.Data.BestRecipesUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0796e1c-2b65-4589-ae38-ec985121887d",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDWQ+9BeuHocSBLyUo3jkoQz/r71LuMukpcJYnlF3LxeAbzfk5+SPiO0q78H+SRBxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db7f88a0-5da8-42d0-9c7d-215913cdf74f",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(5807),
                            DateUpdated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(5823),
                            Description = "Start your meal with delicious appetizers.",
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(5824),
                            DateUpdated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(5825),
                            Description = "Hearty and satisfying main course recipes.",
                            Name = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(5826),
                            DateUpdated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(5826),
                            Description = "Sweet treats to end your meal.",
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Challenge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(6331),
                            DateUpdated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(6332),
                            Details = "Create the most refreshing and healthy summer salad.",
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Salad Challenge",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(6334),
                            DateUpdated = new DateTime(2026, 1, 17, 22, 53, 31, 922, DateTimeKind.Local).AddTicks(6334),
                            Details = "Bake a delicious dessert perfect for the holiday season.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Holiday Dessert Challenge",
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This recipe is fantastic! My family loved it.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6432),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6432),
                            RecipeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "I found the instructions a bit confusing, but the end result was great.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6433),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6434),
                            RecipeId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Delicious! I will definitely make this again.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6435),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6435),
                            RecipeId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Favourite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6500),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6501),
                            RecipeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6502),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6502),
                            RecipeId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 0,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6503),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6504),
                            RecipeId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownVote")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpVote")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Pantry",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "All-Purpose Flour",
                            UpVote = 180
                        },
                        new
                        {
                            Id = 2,
                            Category = "Pantry",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Granulated Sugar",
                            UpVote = 150
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pantry",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 2,
                            Name = "Olive Oil",
                            UpVote = 210
                        },
                        new
                        {
                            Id = 4,
                            Category = "Dairy",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Unsalted Butter",
                            UpVote = 95
                        },
                        new
                        {
                            Id = 5,
                            Category = "Dairy",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Whole Milk",
                            UpVote = 70
                        },
                        new
                        {
                            Id = 6,
                            Category = "Produce",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 1,
                            Name = "Garlic",
                            UpVote = 300
                        },
                        new
                        {
                            Id = 7,
                            Category = "Produce",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 5,
                            Name = "Yellow Onion",
                            UpVote = 120
                        },
                        new
                        {
                            Id = 8,
                            Category = "Spices",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Kosher Salt",
                            UpVote = 400
                        },
                        new
                        {
                            Id = 9,
                            Category = "Spices",
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownVote = 0,
                            Name = "Black Pepper",
                            UpVote = 250
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookingDuration")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("ServingSize")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6014),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6014),
                            Description = "Fluffy and light pancakes perfect for breakfast.",
                            Instructions = "Mix ingredients, cook on griddle, serve with syrup.",
                            IsTrending = false,
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Classic Pancakes",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6016),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6016),
                            Description = "Crisp romaine lettuce with creamy Caesar dressing.",
                            Instructions = "Toss lettuce with dressing, add croutons and cheese.",
                            IsTrending = false,
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Caesar Salad",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CookingDuration = 0,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6017),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6018),
                            Description = "Chewy cookies loaded with chocolate chips.",
                            Instructions = "Mix dough, fold in chocolate chips, bake until golden.",
                            IsTrending = false,
                            PreparationTime = 0,
                            ServingSize = 0,
                            Title = "Chocolate Chip Cookies",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("BestRecipes.Domain.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredient");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6096),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6096),
                            Id = 0,
                            Notes = "sifted",
                            Quantity = 200m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6098),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6098),
                            Id = 0,
                            Notes = "",
                            Quantity = 30m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6099),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6099),
                            Id = 0,
                            Notes = "room temperature",
                            Quantity = 250m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6101),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6101),
                            Id = 0,
                            Notes = "melted",
                            Quantity = 50m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 8,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6102),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6103),
                            Id = 0,
                            Notes = "pinch",
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6105),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6105),
                            Id = 0,
                            Notes = "finely chopped",
                            Quantity = 0.25m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 3,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6106),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6107),
                            Id = 0,
                            Notes = "for dressing",
                            Quantity = 50m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 8,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6108),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6108),
                            Id = 0,
                            Notes = "to taste",
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 9,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6109),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6109),
                            Id = 0,
                            Notes = "freshly ground",
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 1,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6110),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6111),
                            Id = 0,
                            Notes = "sifted",
                            Quantity = 180m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 2,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6112),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6112),
                            Id = 0,
                            Notes = "",
                            Quantity = 100m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 4,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6113),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6113),
                            Id = 0,
                            Notes = "softened",
                            Quantity = 100m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 8,
                            DateCreated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6114),
                            DateUpdated = new DateTime(2026, 1, 17, 14, 53, 31, 922, DateTimeKind.Utc).AddTicks(6115),
                            Id = 0,
                            Notes = "to balance sweetness",
                            Quantity = 0.5m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BestRecipes.Domain.RecipeIngredient", b =>
                {
                    b.HasOne("BestRecipes.Domain.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BestRecipes.Domain.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BestRecipes.Data.BestRecipesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BestRecipes.Domain.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("BestRecipes.Domain.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
